google_analytics_id: UA-84822840-1

repository: https://github.com/BuptFoto/BuptFoto

timezone: Asia/Shanghai

title: BUPT Fotoclub
description: Official Website
url: http://buptfoto.com

author: iROCKBUNNY
author_url: http://irockbunny.com
organization: BUPT Fotoclub
organization_url: http://buptfoto.com/

github: https://github.com/BuptFoto

image: /img/Avatar.png
logo: /img/Avatar.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor